using System;
namespace GRaff.Randomness
{
    /// <summary>
    /// Represents a GRaff.Randomness.IDistribution that generates values by calling a System.Func.
    /// </summary>
    /// <typeparam name="T">The type of elements that are generated by this distribution.</typeparam>
    public class FuncDistribution<T> : IDistribution<T>
    {

        public FuncDistribution(Func<T> generator)
        {
            this.Generator = generator;
        }

        public Func<T> Generator { get; }

        public T Generate() => Generator();
    }
}
